social_network/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('vision/', include('vision.urls')),
    path('admin/', admin.site.urls),
]

vision/urls.py
from django.urls import path
from . import views

app_name = 'vision'
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:post_id>/post_detail", views.post_detail, name="post_detail")
]

vision/models.py
from django.db import models

class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    post_user = models.CharField(max_length=255, null=True, blank=True)
    post_time = models.DateTimeField(null=True, blank=True)
    post_title = models.CharField(max_length=255, null=True, blank=True)
    post_body = models.TextField(null=True, blank=True)
    def __str__(self):
        return self.post_title

vision/views.py
from django.shortcuts import render
from .models import Post

def index(request):
    post_filter = Post.objects.all().order_by("-post_time")
    return render(request, "vision/index.html", {"post_filter":post_filter})

def post_detail(request, post_id):
    post_filter = Post.objects.filter(post_id=post_id)
    return render(request, 'vision/post_detail.html', {"post_filter":post_filter})

vision/templates/vision/index.html
<head>
  <title>Home - Vision</title>
</head>
<header>
  <h1 style="text-align: center">Home</h1>
</header>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'vision/styles.css' %}">

<table style="width:60%" align="center">
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Time</th>
  </tr>
  {% for post in post_filter %}
  <tr>
    <td>{{ post.post_user }}</td>
    <td><a href="{% url 'vision:post_detail' post.post_id %}">{{ post.post_title }}</a></td>
    <td>{{ post.post_time }}</td>
  </tr>
  {% endfor %}
</table>

vision/templates/vision/post_detail.html
<head>
  {% for post in post_filter %}
  <title>{{ post.post_title }} - Vision</title>
</head>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'vision/styles.css' %}">

<table style="width:60%" align="center">
  <tr>
    <th id="top">{{ post.post_user }} - {{ post.post_title }}</th>
  </tr>
</table>

<p class="postbody">{{ post.post_body }}</p>
{% endfor %}

<table>
  <tr>
    <td style="border: 2px solid"><a href="#top">Top of page</a></td>
    <td style="border: 2px solid"><a href="{% url 'vision:index' %}">Back to index</a></td>
  </tr>
</table>